# -*- coding: utf-8 -*-
"""kobert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123FNJj1jTRGDTrYoI-3_tpcPQs2eFDX6
"""

!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers==3 # 최신 버전으로 설치하면 "Input: must be Tensor, not str" 라는 에러 발생
!pip install torch

!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master

import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model

from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup

##GPU 사용 시
device = torch.device("cuda:0")

bertmodel, vocab = get_pytorch_kobert_model()

# 학습용 데이터셋 불러오기
import pandas as pd

td_hate = pd.read_csv('/content/drive/MyDrive/케글/train.hate.csv')
td_hate.head
td_hate

dev_hate = pd.read_csv('/content/drive/MyDrive/케글/dev.hate.csv')
dev_hate.head
dev_hate.info()

td_hate['label'].value_counts().plot(kind='bar')

print(td_hate.groupby('label').size().reset_index(name='count'))

td_hate['comments']= td_hate['comments'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
td_hate['comments'] = td_hate['comments'].str.replace('^ +', "")
td_hate['comments'].replace('', np.nan, inplace=True)
print(td_hate.isnull().sum())

dev_hate['comments']= dev_hate['comments'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
dev_hate['comments'] = dev_hate['comments'].str.replace('^ +', "")
dev_hate['comments'].replace('', np.nan, inplace=True)
print(dev_hate.isnull().sum())

dev_hate.info()
print('')
print('----')
td_hate.info()

# 욕 강도 추출
data1 = td_hate.loc[td_hate['label'] == 'none']
data2 = td_hate.loc[td_hate['label'] == 'offensive']
data3 = td_hate.loc[td_hate['label'] == 'hate']

new_td_hate = data1.append([data2,data3],sort=False)
new_td_hate = pd.DataFrame(new_td_hate)
new_td_hate.head()

new_dev_hate = data1.append([data2,data3],sort=False)
new_dev_hate = pd.DataFrame(new_dev_hate)
new_dev_hate.head()

# td_hate 욕 강도 라벨링

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(new_td_hate['label'])
new_td_hate['label'] = encoder.fit_transform(new_td_hate['label'])
new_td_hate.info()

# dev_hate 욕 강도 추출
data1 = dev_hate.loc[td_hate['label'] == 'none']
data2 = dev_hate.loc[td_hate['label'] == 'offensive']
data3 = dev_hate.loc[td_hate['label'] == 'hate']

new_dev_hate = data1.append([data2,data3],sort=False)
new_dev_hate = pd.DataFrame(new_dev_hate)
new_dev_hate.head()

encoder = LabelEncoder()
encoder.fit(new_dev_hate['label'])
new_dev_hate['label'] = encoder.transform(new_dev_hate['label'])
new_dev_hate.head()
new_dev_hate.info()

# 라벨링 된 욕 강도 매핑  --> {0: 'hate', 1: 'none', 2: 'offensive'}

mapping = dict(zip(range(len(encoder.classes_)), encoder.classes_))
mapping

# 기본 Bert tokenizer 사용
tokenizer = get_tokenizer()
tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)



#에러 
 '''
 138번 에러
 class BERTDataset(Dataset): 에러      
        #[에러1:138번] self.labels = [np.int32(i[label_idx]) for i in dataset] 로 하니까 
        
        158번에서 
        data_train = BERTDataset(td_hate, 0, 1, tok, max_len, True, False) 에러1발생
        # 에러1:  ValueError: invalid literal for int() with base 10: 'o'

        # 그래서 np.int32(i[label_idx]) --> np.str(i[label_idx]) 스트링 형태로 형변환
        # self.labels = [np.str(i[label_idx]) for i in dataset]
'''

class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len,
                 pad, pair):
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)

        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        
        # 에러 ValueError: invalid literal for int() with base 10: 'o'
        # np.int32(i[label_idx]) --> np.str(i[label_idx])
        self.labels = [np.str(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

# Setting parameters
max_len = 64 # 해당 길이를 초과하는 단어에 대해선 bert가 학습하지 않음
batch_size = 64
warmup_ratio = 0.1
num_epochs = 5
max_grad_norm = 1
log_interval = 200
learning_rate = 5e-5

# self.labels = [np.int32(i[label_idx]) for i in dataset
#에러 :ValueError: invalid literal for int() with base 10: 'o'
data_train = BERTDataset(td_hate, 0, 1, tok, max_len, True, False)
data_test = BERTDataset(dev_hate, 0, 1, tok, max_len, True, False)

# pytorch용 DataLoader 사용
train_dataloader = torch.utils.data.DataLoader(data_train, batch_size=batch_size, num_workers=5)
dev_dataloader = torch.utils.data.DataLoader(data_test, batch_size=batch_size, num_workers=5)

class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes = 3, # softmax 사용 <- binary일 경우는 2
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

model = BERTClassifier(bertmodel, dr_rate=0.5).to(device)

# Prepare optimizer and schedule (linear warmup and decay)
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

# 옵티마이저 선언
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss() # softmax용 Loss Function 정하기 <- binary classification도 해당 loss function 사용 가능

t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

# 학습 평가 지표인 accuracy 계산 -> 얼마나 타겟값을 많이 맞추었는가
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

#[235번 에러] 
#에러2 :   #AttributeError: 'tuple' object has no attribute 'long'
#        label = label.long().to(device)


# 모델 학습 시작
for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length

        #AttributeError: 'tuple' object has no attribute 'long'
        label = label.long().to(device)
        
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm) # gradient clipping
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
